<a href="https://colab.research.google.com/github/DineishVS/dineishcommunity/blob/main/credit_card_fraud_detection.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [30]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from keras.layers import concatenate

In [5]:
credit_card_data=pd.read_csv("creditcard.csv")

In [6]:
credit_card_data.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0.0
1,0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0.0
2,1,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0.0
3,1,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0.0
4,2,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0.0

In [7]:
credit_card_data.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
27814,34711,1.443955,-1.052462,-0.141721,-1.564017,-0.966274,-0.333886,-0.777060,0.023616,-2.168826,...,-0.479940,-1.165220,0.155226,-0.409701,0.179672,-0.446258,0.004329,0.000060,32.39,0.0
27815,34711,-0.263364,0.931818,1.193111,-0.507924,0.862019,0.249381,0.815449,-0.090801,-0.520583,...,-0.310112,-0.648621,-0.253746,-1.030111,-0.046091,0.107328,0.101296,-0.124600,1.49,0.0
27816,34712,0.976345,-1.024867,0.978714,0.639442,-1.413711,0.311635,-0.909035,0.232423,-0.493025,...,-0.279978,-0.599463,-0.081403,-0.059427,0.202311,-0.405753,0.055109,0.052975,151.00,0.0
27817,34712,1.464604,-0.437919,-0.018869,-1.057177,-0.154243,0.251215,-0.584866,-0.025483,-0.841369,...,-0.148384,-0.454571,-0.019732,-1.313689,0.379650,-0.368497,0.031746,0.007238,8.00,0.0
27818,34,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
credit_card_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27819 entries, 0 to 27818
Data columns (total 31 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Time    27819 non-null  int64
 1   V1      27818 non-null  float64
 2   V2      27818 non-null  float64
 3   V3      27818 non-null  float64
 4   V4      27818 non-null  float64
 5   V5      27818 non-null  float64
 6   V6      27818 non-null  float64
 7   V7      27818 non-null  float64
 8   V8      27818 non-null  float64
 9   V9      27818 non-null  float64
 10  V10     27818 non-null  float64
 11  V11     27818 non-null  float64
 12  V12     27818 non-null  float64
 13  V13     27818 non-null  float64
 14  V14     27818 non-null  float64
 15  V15     27818 non-null  float64
 16  V16     27818 non-null  float64
 17  V17     27818 non-null  float64
 18  V18     27818 non-null  float64
 19  V19     27818 non-null  float64
 20  V20     27818 non-null  float64
 21  V21     27818 non-null  float64
 22  V22     27818 non-null  float64
 23  V23     27818 non-null  float64
 24  V24     27818 non-null  float64
 25  V25     27818 non-null  float64
 26  V26     27818 non-null  float64
 27  V27     27818 non-null  float64
 28  V28     27818 non-null  float64
 29  Amount  27818 non-null  float64
 30  Class   27818 non-null  float64
dtypes: float64(30), int64(1)
memory usage: 6.6 MB

In [10]:
credit_card_data.isnull().sum()

Time      0
V1        1
V2        1
V3        1
V4        1
V5        1
V6        1
V7        1
V8        1
V9        1
V10       1
V11       1
V12       1
V13       1
V14       1
V15       1
V16       1
V17       1
V18       1
V19       1
V20       1
V21       1
V22       1
V23       1
V24       1
V25       1
V26       1
V27       1
V28       1
Amount    1
Class     1
dtype: int64

In [11]:
credit_card_data['Class'].value_counts()

0.0    27725
1.0       93
Name: Class, dtype: int64

In [13]:
legit=credit_card_data[credit_card_data.Class == 0]
frawd=credit_card_data[credit_card_data.Class == 1]

In [14]:
print(legit.shape)
print(frawd.shape)

(27725, 31)
(93, 31)

In [16]:
legit.Amount.describe()

count    27725.000000
mean        77.232517
std        219.509762
min          0.000000
25%          6.490000
50%         19.950000
75%         69.320000
max       7879.420000
Name: Amount, dtype: float64

In [17]:
frawd.Amount.describe()

count      93.000000
mean       96.609677
std       259.128010
min         0.000000
25%         1.000000
50%         1.100000
75%        99.990000
max      1809.680000
Name: Amount, dtype: float64

In [18]:
credit_card_data.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0.0,20440.754518,-0.190595,0.129284,0.765200,0.201632,-0.180681,0.092904,-0.099318,0.014884,0.405538,...,0.041673,-0.037007,-0.125822,-0.040202,0.011510,0.129192,0.022983,0.010650,0.003732,77.232517
1.0,18829.451613,-8.165086,6.134379,-11.690379,6.070066,-5.753486,-2.388962,-7.986805,4.121062,-2.922478,...,0.697894,0.549621,-0.372248,-0.340859,-0.260055,0.359772,0.179521,0.832824,0.100500,96.609677

In [19]:
legit_sample=legit.sample(n=93)

In [41]:
new_dataset=pd.concat([legit_sample,frawd],axis=0)

In [33]:
print(new_dataset)

tf.Tensor(
[[ 2.07100000e+03  1.15807850e+00 -2.02637926e-01 ...  3.21606348e-02
   4.95900000e+01  0.00000000e+00]
 [ 1.96010000e+04 -1.74707656e+00 -7.34115947e-01 ...  1.21786368e-01
   5.00000000e+00  0.00000000e+00]
 [ 3.92700000e+03  1.38798694e+00 -2.89438823e-01 ... -1.38792640e-02
   4.49000000e+01  0.00000000e+00]
 ...
 [ 3.46340000e+04  3.33499491e-01  1.69987345e+00 ...  3.05473420e-01
   1.89600000e+01  1.00000000e+00]
 [ 3.46840000e+04 -2.43923697e+00  2.59145816e+00 ... -7.43712586e-01
   1.25300000e+02  1.00000000e+00]
 [ 3.46870000e+04 -8.60826892e-01  3.13178963e+00 ...  6.91195096e-01
   1.90200000e+01  1.00000000e+00]], shape=(186, 31), dtype=float64)

In [43]:
new_dataset.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
2498,2071,1.158078,-0.202638,0.456260,0.443970,-0.526036,-0.225323,-0.151647,-0.017965,-1.628438,...,-0.707052,-1.687483,0.303325,0.129808,0.019843,-0.842859,0.046494,0.032161,49.59,0.0
11276,19601,-1.747077,-0.734116,2.013521,-0.100606,1.979508,0.014477,-0.687602,0.591228,1.089454,...,-0.123684,-0.544428,0.459981,-0.745741,-0.689687,0.051321,0.029156,0.121786,5.00,0.0
4582,3927,1.387987,-0.289439,-0.307632,-0.763133,-0.027845,-0.238347,-0.145230,-0.281419,-0.207016,...,-0.908571,-2.011627,0.063570,-0.896783,0.180200,0.685150,-0.111782,-0.013879,44.90,0.0
23694,32872,-1.628962,-0.178669,1.446585,-1.692559,-0.561857,1.137220,-0.033672,0.701262,1.629056,...,-0.016869,0.173863,-0.454938,-1.251503,0.760111,-0.564793,-0.029309,-0.075690,150.00,0.0
978,741,-1.460494,1.072256,1.525621,0.122964,-0.874790,-0.382503,0.025338,0.353055,0.923318,...,0.037687,0.534206,-0.218095,0.429192,-0.068667,0.428325,0.159005,0.040868,29.99,0.0

In [44]:
new_dataset.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
26802,34256,0.539276,1.554890,-2.066180,3.241617,0.184736,0.028330,-1.515521,0.537035,-1.999846,...,0.371773,0.111955,-0.305225,-1.053835,0.771175,0.240878,0.418435,0.232170,19.02,1.0
27362,34521,1.081234,0.416414,0.862919,2.520863,-0.005021,0.563341,-0.123372,0.223122,-0.673598,...,-0.159387,-0.305154,0.053620,0.011761,0.375146,-0.106299,0.021008,0.010559,1.52,1.0
27627,34634,0.333499,1.699873,-2.596561,3.643945,-0.585068,-0.654659,-2.275789,0.675229,-2.042416,...,0.469212,-0.144363,-0.317981,-0.769644,0.807855,0.228164,0.551002,0.305473,18.96,1.0
27738,34684,-2.439237,2.591458,-2.840126,1.286244,-1.777016,-1.436139,-2.206056,-2.282725,-0.292885,...,1.774460,-0.771390,0.065727,0.103916,-0.057578,0.242652,-0.268649,-0.743713,125.30,1.0
27749,34687,-0.860827,3.131790,-5.052968,5.420941,-2.494141,-1.811287,-5.479117,1.189472,-3.908206,...,1.192694,0.090356,-0.341881,-0.215924,1.053032,0.271139,1.373300,0.691195,19.02,1.0

In [48]:
new_dataset.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0.0,17588.032258,-0.602936,0.139116,0.609229,0.345647,-0.461055,0.147329,-0.129936,0.018625,0.585723,...,0.130083,0.017888,-0.182664,-0.089118,-0.004275,0.148693,-0.015761,0.087667,0.074885,145.842903
1.0,18829.451613,-8.165086,6.134379,-11.690379,6.070066,-5.753486,-2.388962,-7.986805,4.121062,-2.922478,...,0.697894,0.549621,-0.372248,-0.340859,-0.260055,0.359772,0.179521,0.832824,0.100500,96.609677

In [49]:
X = new_dataset.drop(columns='Class',axis=1)
Y = new_dataset['Class']

In [50]:
print(X)

        Time        V1        V2        V3        V4        V5        V6  \
2498    2071  1.158078 -0.202638  0.456260  0.443970 -0.526036 -0.225323
11276  19601 -1.747077 -0.734116  2.013521 -0.100606  1.979508  0.014477
4582    3927  1.387987 -0.289439 -0.307632 -0.763133 -0.027845 -0.238347
23694  32872 -1.628962 -0.178669  1.446585 -1.692559 -0.561857  1.137220
978      741 -1.460494  1.072256  1.525621  0.122964 -0.874790 -0.382503
...      ...       ...       ...       ...       ...       ...       ...
26802  34256  0.539276  1.554890 -2.066180  3.241617  0.184736  0.028330
27362  34521  1.081234  0.416414  0.862919  2.520863 -0.005021  0.563341
27627  34634  0.333499  1.699873 -2.596561  3.643945 -0.585068 -0.654659
27738  34684 -2.439237  2.591458 -2.840126  1.286244 -1.777016 -1.436139
27749  34687 -0.860827  3.131790 -5.052968  5.420941 -2.494141 -1.811287

             V7        V8        V9  ...       V20       V21       V22  \
2498  -0.151647 -0.017965 -1.628438  ... -0.440099 -0.707052 -1.687483
11276 -0.687602  0.591228  1.089454  ...  0.006466 -0.123684 -0.544428
4582  -0.145230 -0.281419 -0.207016  ... -0.337574 -0.908571 -2.011627
23694 -0.033672  0.701262  1.629056  ... -0.096618 -0.016869  0.173863
978    0.025338  0.353055  0.923318  ...  0.194302  0.037687  0.534206
...         ...       ...       ...  ...       ...       ...       ...
26802 -1.515521  0.537035 -1.999846  ...  0.302735  0.371773  0.111955
27362 -0.123372  0.223122 -0.673598  ... -0.165249 -0.159387 -0.305154
27627 -2.275789  0.675229 -2.042416  ...  0.329342  0.469212 -0.144363
27738 -2.206056 -2.282725 -0.292885  ...  0.513530  1.774460 -0.771390
27749 -5.479117  1.189472 -3.908206  ...  1.085760  1.192694  0.090356

            V23       V24       V25       V26       V27       V28  Amount
2498   0.303325  0.129808  0.019843 -0.842859  0.046494  0.032161   49.59
11276  0.459981 -0.745741 -0.689687  0.051321  0.029156  0.121786    5.00
4582   0.063570 -0.896783  0.180200  0.685150 -0.111782 -0.013879   44.90
23694 -0.454938 -1.251503  0.760111 -0.564793 -0.029309 -0.075690  150.00
978   -0.218095  0.429192 -0.068667  0.428325  0.159005  0.040868   29.99
...         ...       ...       ...       ...       ...       ...     ...
26802 -0.305225 -1.053835  0.771175  0.240878  0.418435  0.232170   19.02
27362  0.053620  0.011761  0.375146 -0.106299  0.021008  0.010559    1.52
27627 -0.317981 -0.769644  0.807855  0.228164  0.551002  0.305473   18.96
27738  0.065727  0.103916 -0.057578  0.242652 -0.268649 -0.743713  125.30
27749 -0.341881 -0.215924  1.053032  0.271139  1.373300  0.691195   19.02

[186 rows x 30 columns]

In [51]:
print(Y)

2498     0.0
11276    0.0
4582     0.0
23694    0.0
978      0.0
        ...
26802    1.0
27362    1.0
27627    1.0
27738    1.0
27749    1.0
Name: Class, Length: 186, dtype: float64

In [53]:
X_train, X_test, Y_train, Y_test = train_test_split(X,Y, test_size=0.2, stratify=Y,random_state=2)

In [54]:
print(X.shape, X_train.shape, X_test.shape)

(186, 30) (148, 30) (38, 30)

In [55]:
model=LogisticRegression()

In [60]:
model.fit(X_train, Y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [61]:
X_train_prediction= model.predict(X_train)
training_data_accuracy = accuracy_score(X_train_prediction,Y_train)

In [62]:
print("Accuracy on training data :", training_data_accuracy)

Accuracy on training data : 0.9594594594594594

In [67]:
X_test_prediction = model.predict(X_test)
training_data_accuracy = accuracy_score(X_test_prediction, Y_test)

In [68]:
print("Accuracy score on TEst Data : ", training_data_accuracy )

Accuracy score on TEst Data :  0.9473684210526315